# --- Do not remove these libs ---
from freqtrade.optimize.space import Dimension, SKDecimal
from pandas import DataFrame
import math
import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.strategy import IStrategy, merge_informative_pair, IntParameter, DecimalParameter

class Quickbro9(IStrategy):
    """
    Quickbro strategy version 9:
    - ROI generated by vertex-form quadratic f(x) = a*(x - h)^2 + k
    - Domain [0, range_days] days; range_days hyperoptable (0.1 to 10)
    - ROI range [roi_min, roi_max] hyperoptable
    - Samples ROI at 10 equidistant points across domain, keys in minutes
    - Hyperoptable lookback_days for rolling low/high logic
    - Buy when price crosses above rolling low; Sell when price crosses above rolling high
    - Stoploss set to 20%
    """
    class HyperOpt:
        @staticmethod
        def roi_space() -> list[Dimension]:
            # range_days in days, roi_min and roi_max (0 to 1)
            return [
                SKDecimal(0.1, 10.0, decimals=2, name='range_days'),
                SKDecimal(0.0, 1.0, decimals=4, name='roi_min'),
                SKDecimal(0.0, 1.0, decimals=4, name='roi_max'),
            ]

        @staticmethod
        def generate_roi_table(params: dict) -> dict[int, float]:
            rd = params['range_days']
            y_min = params['roi_min']
            y_max = params['roi_max']
            # Domain midpoint and half-width (in days)
            h = rd / 2.0
            d = rd / 2.0
            # Vertex form: f(x) = a*(x - h)^2 + k, with k = y_max (peak)
            k = y_max
            # Compute a so that f(0) = y_min: a * (0 - h)^2 + k = y_min
            a = (y_min - k) / (d * d) if d != 0 else 0.0
            # Sample 10 equidistant x values in [0, rd]
            roi_table = {}
            for i in range(10):
                x = 0.0 + i * (rd - 0.0) / 9.0
                t = int(x * 24 * 60)  # convert days to minutes
                if t < 0:
                    continue
                y = a * (x - h)**2 + k
                roi_table[t] = float(y)
            return dict(sorted(roi_table.items()))

    # Hyperoptable lookback window (in days)
    lookback_days = IntParameter(1, 200, default=126, space='buy')

    # Stoploss set to 20%
    stoploss = -0.20

    # Primary and informative timeframes
    timeframe = '15m'
    inf_timeframe = '1d'

    # ROI fallback (unused during hyperopt)
    minimal_roi = {
        "0": 0.01,
        "120": 0.02,
        "480": 0.05,
        "1440": 0.10
    }

    # Sell settings
    use_sell_signal = True
    sell_profit_only = True
    ignore_roi_if_buy_signal = False

    # Startup candles
    startup_candle_count = 127
    process_only_new_candles = False

    def informative_pairs(self):
        # Fetch daily candles for all whitelisted pairs
        return [(pair, self.inf_timeframe) for pair in self.dp.current_whitelist()]

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Compute rolling low/high for each lookback_days on daily data
        informative = self.dp.get_pair_dataframe(
            pair=metadata['pair'], 
            timeframe=self.inf_timeframe
        )
        for lb in self.lookback_days.range:
            low_col = f"{lb}d-low"
            high_col = f"{lb}d-high"
            informative[low_col] = informative['close'].rolling(window=lb, min_periods=1).min()
            informative[high_col] = informative['close'].rolling(window=lb, min_periods=1).max()
        return merge_informative_pair(dataframe, informative, self.timeframe, self.inf_timeframe, ffill=True)

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Buy when price crosses above rolling low
        lb = self.lookback_days.value
        low_col = f"{lb}d-low_{self.inf_timeframe}"
        dataframe.loc[
            qtpylib.crossed_above(dataframe['close'], dataframe[low_col]),
            'buy'
        ] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Sell when price crosses above rolling high
        lb = self.lookback_days.value
        high_col = f"{lb}d-high_{self.inf_timeframe}"
        dataframe.loc[
            qtpylib.crossed_above(dataframe['close'], dataframe[high_col]),
            'sell'
        ] = 1
        return dataframe
